---
dist: xenial
language: python
python: "3.6"

sudo: true

env:
  global:
    - containers: pg-93,pg-10
  matrix:
    - test_os: centos7
    - test_os: ubuntu16.04
      debug: true
    - test_os: ubuntu14.04
    - test_os: debian9
  - test_os: debian10

install:
  # Cloning testing template
  - sudo mkdir /etc/ansible
  - sudo chown -R "${USER}:" /etc/ansible
  - git clone https://github.com/Nani-o/ansible-template-role-test /etc/ansible

script:
  # Run tests.
  - bash /etc/ansible/test.sh
