---
- name: Check if a db is already installed
  stat:
    path: "{{ postgresql_datadir }}/PG_VERSION"
  register: postgresql_datadir_init_check

- block:
    - name: Create the datadir
      file:
        path: "{{ postgresql_datadir }}"
        owner: "{{ postgresql_user }}"
        group: "{{ postgresql_group }}"
        recurse: yes
        state: directory      

    - name: Init the db
      shell: "{{ postgresql_initdb_command }} -D {{ postgresql_datadir }}"
      become: yes
      become_user: "{{ postgresql_user }}"
  when: not postgresql_datadir_init_check.stat.exists
