---
- block:
  - name: Include OS-specific variables
    include_vars:
      dir: "vars"
      files_matching: "{{ item }}"
    with_items:
      - "{{ ansible_os_family }}.yml"
      - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    tags:
      - postgresql_install
      - postgresql_init

  - include_tasks: install.yml
    tags: postgresql_install
    
  - include_tasks: init.yml
    tags: postgresql_init
  tags: postgresql
