---
- block:
  - name: Include OS-specific variables.
    include_vars: "{{ lookup('first_found', params) }}"
    vars:
      params:
        files:
          - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
          - "{{ ansible_os_family }}.yml"
        path:
          - 'vars'
    tags:
      - postgresql_install
      - postgresql_init

  - import_tasks: packages.yml
    tags: postgresql_install

  - import_tasks: init.yml
    when: "ansible_os_family == 'RedHat'"
    tags: postgresql_init
  tags: postgresql